run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - unconvert
    - goconst
    - goimports
    - misspell
    - prealloc
    - gocritic
    - gofmt
    - revive
    - exportloopref