package bybit

const (
	BybitMainnetBaseURL  = "https://api.bybit.com"
	BytickMainnetBaseURL = "https://api.bytick.com"
	BybitTestnetBaseURL  = "https://api-testnet.bybit.com"

	/* Spot Market API */
	PublicServerTimePath                = "/spot/v1/time"
	PublicSpotSymbolsPath               = "/spot/v1/symbols"
	PublicSpotQuoteDepthPath            = "/spot/quote/v1/depth"
	PublicSpotQuoteDepthMergedPath      = "/spot/quote/v1/depth/merged"
	PublicSpotQuoteTradesPath           = "/spot/quote/v1/trades"
	PublicSpotQuoteKlinePath            = "/spot/quote/v1/kline"
	PublicSpotQuoteTicker24HrPath       = "/spot/quote/v1/ticker/24hr"
	PublicSpotQuoteTickerPrice          = "/spot/quote/v1/ticker/price"
	PublicSpotQuoteTickerBookTickerPath = "/spot/quote/v1/ticker/book_ticker"

	/* Spot Account API */
	PrivateSpotOrderPath                = "/spot/v1/order"
	PrivateSpotOrderFastPath            = "/spot/v1/order/fast"
	PrivateSpotOrderBatchCancelPath     = "/spot/order/batch-cancel"
	PrivateSpotOrderBatchFastCancelPath = "/spot/order/batch-fast-cancel"
	PrivateSpotBatchCancelByIdsPath     = "/spot/order/batch-cancel-by-ids"
	PrivateOpenOrdersPath               = "/spot/v1/open-orders"
	PrivateOrderHistoryPath             = "/spot/v1/history-orders"
	PrivateTradeHistoryPath             = "/spot/v1/myTrades"

	/* Spot Wallet API */
	PrivateWalletBalancePath = "/spot/v1/account"

	/* USDT Perpetual Market API */
	PublicLinearOrderBookPath                   = "v2/public/orderBook/L2"
	PublicLinearQueryKlinePath                  = "/public/linear/kline"
	PublicLinearGetSymbolInformationPath        = "/v2/public/tickers"
	PublicLinearGetPublicTradingRecordsPath     = "/public/linear/recent-trading-records"
	PublicLinearGetLastFundingRatePath          = "/public/linear/funding/prev-funding-rate"
	PublicLinearQuerySymbolPath                 = "/v2/public/symbols"
	PublicLinearLiquidatedOrdersPath            = "/v2/public/liq-records"
	PublicLinearQueryMarkPriceKline             = "/public/linear/mark-price-kline"
	PublicLinearQueryIndexPriceKlinePath        = "/v2/public/index-price-kline"
	PublicLinearQueryPremiumIndexPriceKlinePath = "/v2/public/premium-index-kline"
	PublicLinearGetOpenInterestPath             = "/v2/public/open-interest"
	PublicLinearGetLatestBigDealPath            = "/v2/public/big-deal"
	PublicLinearGetLongShortRatioPath           = "/v2/public/account-ratio"

	// USDT Perpetual
	PrivateLinearPlaceOrderPath                  = "/private/linear/order/create"
	PrivateLinearGetActiveOrderPath              = "/private/linear/order/list"
	PrivateLinearOrderCancelPath                 = "/private/linear/order/cancel"
	PrivateLinearOrderCancelAllPath              = "/private/linear/order/cancel-all"
	PrivateLinearReplaceActiveOrderPath          = "/private/linear/order/replace"
	PrivateLinearQueryActiveOrderPath            = "/private/linear/order/search"
	PrivateLinearPlaceConditionalOrderPath       = "/private/linear/stop-order/create"
	PrivateLinearGetConditionalOrderPath         = "/private/linear/stop-order/list"
	PrivateLinearCancelConditionalOrderPath      = "/private/linear/stop-order/cancel"
	PrivateLinearCancelAllConditionalOrderPath   = "/private/linear/stop-order/cancel-all"
	PrivateLinearReplaceConditionalOrderPath     = "/private/linear/stop-order/replace"
	PrivateLinearQueryConditionalOrderPath       = "/private/linear/stop-order/search"
	PrivateLinearGetPositionPath                 = "/private/linear/position/list"
	PrivateLinearSetAutoAddMarginPath            = "/private/linear/position/set-auto-add-margin"
	PrivateLinearSwitchMarginPath                = "/private/linear/position/switch-isolated"
	PrivateLinearSwitchPositionModePath          = "/private/linear/position/switch-mode"
	PrivateLinearPositionTpSlSwitch              = "/private/linear/tpsl/switch-mode"
	PrivateLinearAddReduceMarginPath             = "/private/linear/position/add-margin"
	PrivateLinearSetLeveragePath                 = "/private/linear/position/set-leverage"
	PrivateLinearSetTradingStopPath              = "/private/linear/position/trading-stop"
	PrivateLinearGetUserTradeRecordsPath         = "/private/linear/trade/execution/list"
	PrivateLinearGetExtendedUserTradeRecordsPath = "/private/linear/trade/execution/history-list"
	PrivateLinearGetClosedProfitLossPath         = "/private/linear/trade/closed-pnl/list"
	PublicLinearGetRiskLimitPath                 = "/public/linear/risk-limit"
	PrivateLinearSetRiskLimitPath                = "/private/linear/position/set-risk"
	PrivateLinearPredictedFundingRatePath        = "/private/linear/funding/predicted-funding"
	PrivateLinearGetLastFundingFeePath           = "/private/linear/funding/prev-funding"
	// nolint:gosec
	PrivateLinearGetAPIKeyInfoPath        = "/v2/private/account/api-key"
	PrivateLinearGetLCPInfoPath           = "/v2/private/account/lcp"
	PrivateLinearGetWalletBalancePath     = "/v2/private/wallet/balance"
	PrivateLinearGetWalletFundRecordsPath = "/v2/private/wallet/fund/records"
	PrivateLinearGetWithdrawRecordsPath   = "/v2/private/wallet/withdraw/list"
	PrivateLinearAssetExchangeRecordsPath = "/v2/private/exchange-order/list"

	/* Inverse Perpetual Account API */
	PublicInversePerpetualOrderBookPath              = "/v2/public/orderBook/L2"
	PublicInversePerpetualQueryKlinePath             = "/v2/public/kline/list"
	PublicInversePerpetualSymbolInformationPath      = "/v2/public/tickers"
	PublicInversePerpetualPublicTradingRecordsPath   = "/v2/public/trading-records"
	PublicInversePerpetualQuerySymbolPath            = "/v2/public/symbols"
	PublicInversePerpetualQueryMarkPriceKlinePath    = "/v2/public/mark-price-kline"
	PublicInversePerpetualQueryIndexPriceKlinePath   = "/v2/public/index-price-kline"
	PublicInversePerpetualQueryPremiumIndexKlinePath = "/v2/public/premium-index-kline"
	PublicInversePerpetualOpenInterestPath           = "/v2/public/open-interest"
	PublicInversePerpetualLatestBigDealPath          = "/v2/public/big-deal"
	PublicInversePerpetualLongShortRatioPath         = "/v2/public/account-ratio"

	PrivateInversePerpetualWalletBalancePath     = "/v2/private/wallet/balance"
	PrivateInversePerpetualWalletFundRecordsPath = "/v2/private/wallet/fund/records"
	PrivateInversePerpetualWithdrawRecordsPath   = "/v2/private/wallet/withdraw/list"
	PrivateInversePerpetualAssetExchangeRecords  = "/v2/private/exchange-order/list"

	/* Inverse Perpetual Market API */
	PrivateInversePerpetualPlaceActiveOrderPath      = "/v2/private/order/create"
	PrivateInversePerpetualGetActiveOrderPath        = "/v2/private/order/list"
	PrivateInversePerpetualCancelActiveOrderPath     = "/v2/private/order/cancel"
	PrivateInversePerpetualCancelAllActiveOrdersPath = "/v2/private/order/cancelAll"
	PrivateInversePerpetualReplaceActiveOrderPath    = "/v2/private/order/replace"
	PrivateInversePerpetualQueryActiveOrderPath      = "/v2/private/order"

	PrivateInversePerpetualPlaceConditionalOrderPath      = "/v2/private/stop-order/create"
	PrivateInversePerpetualGetConditionalOrderPath        = "/v2/private/stop-order/list"
	PrivateInversePerpetualCancelConditionalOrderPath     = "/v2/private/stop-order/cancel"
	PrivateInversePerpetualCancelAllConditionalOrdersPath = "/v2/private/stop-order/cancelAll"
	PrivateInversePerpetualReplaceConditionalOrderPath    = "/v2/private/stop-order/replace"
	PrivateInversePerpetualQueryConditionalOrderPath      = "/v2/private/stop-order"

	PrivateInversePerpetualGetPositionPath         = "/v2/private/position/list"
	PrivateInversePerpetualChangeMarginPath        = "/v2/private/position/change-position-margin"
	PrivateInversePerpetualSetTradingStopPath      = "/v2/private/position/trading-stop"
	PrivateInversePerpetualSetLeveragePath         = "/v2/private/position/trading-stop"
	PrivateInversePerpetualGetUserTradeRecordsPath = "/v2/private/execution/list"
	PrivateInversePerpetualClosedProfitLossPath    = "/v2/private/trade/closed-pnl/list"
	PrivateInversePerpetualPositionTpSlSwitchPath  = "/v2/private/tpsl/switch-mode"
	PrivateInversePerpetualMarginSwitchPath        = "/v2/private/position/switch-isolated"
	PrivateInversePerpetualQueryTradingFeeRatePath = "/v2/private/position/fee-rate"

	PrivateInversePerpetualGetRiskLimitPath        = "/v2/public/risk-limit/list"
	PrivateInversePerpetualSetRiskLimitPath        = "/v2/private/position/risk-limit"
	PrivateInversePerpetualGetLastFundingRatePath  = "/v2/public/funding/prev-funding-rate"
	PrivateInversePerpetualGetLastFundingFeePath   = "/v2/private/funding/prev-funding"
	PrivateInversePerpetualGetPredictedFundingPath = "/v2/private/funding/predicted-funding"
	// nolint:gosec
	PrivateInversePerpetualGetAPIKeyInfoPath = "/v2/private/account/api-key"
	PrivateInversePerpetualGetLCPInfoPath    = "/v2/private/account/lcp"
)
