name: Code check

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
      BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: go mod vendor

      # Go
      - name: Setup Go and Test
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - run: go test ./... -coverpkg=./... -coverprofile=coverage.out
      - run: go vet ./... 2> govet.out || true # Ignore go vet status code

  lint-check:
    name: lint-check
    runs-on: ubuntu-latest
    env:
      BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
      BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: go mod vendor

      - name: lint check
        run: make lint
